import { useSuspenseQuery } from "@tanstack/react-query";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { LoaderCircle, ShoppingBag } from "lucide-react";
import { useState, type FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Textarea } from "@/components/ui/textarea";
import { useCart } from "@/lib/cart";
import { placeOrder, type PlaceOrderInput } from "@/lib/orders.functions";
import { siteQueryOptions } from "@/lib/site-query";
import { formatPrice, PAYMENT_METHODS } from "@/lib/site";

export const Route = createFileRoute("/checkout")({ loader: ({ context }) => context.queryClient.ensureQueryData(siteQueryOptions()), head: () => ({ meta: [{ title: "Checkout — Mumtaz Foods" }, { name: "description", content: "Complete your Mumtaz Foods delivery or pickup order." }, { property: "og:title", content: "Checkout — Mumtaz Foods" }, { property: "og:description", content: "Complete your restaurant order." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: CheckoutPage });

function CheckoutPage(){
  const cart=useCart();const {data}=useSuspenseQuery(siteQueryOptions());const submitOrder=useServerFn(placeOrder);const navigate=useNavigate();
  const [orderType,setOrderType]=useState<"delivery"|"pickup">("delivery");const [payment,setPayment]=useState<"cash"|"bank_transfer">("cash");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  const fee=orderType==="delivery"?Number(data.settings?.delivery_fee??0):0;
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");setBusy(true);const form=new FormData(event.currentTarget);const input:PlaceOrderInput={customer_name:String(form.get("name")??""),phone:String(form.get("phone")??""),email:String(form.get("email")??""),order_type:orderType,address:String(form.get("address")??""),area:String(form.get("area")??""),landmark:String(form.get("landmark")??""),notes:String(form.get("notes")??""),payment_method:payment,coupon_code:String(form.get("coupon")??""),items:cart.items.map(item=>({product_id:item.product_id,item_name:item.name,quantity:item.quantity,options:item.options,special_instructions:item.instructions??null}))};try{const result=await submitOrder({data:input});window.localStorage.setItem("mumtaz-foods-latest-order",JSON.stringify(result));cart.clear();await navigate({to:"/order-confirmation"});}catch(reason){setError(reason instanceof Error?reason.message:"We couldn't place your order. Please try again.");setBusy(false)}}
  if(!cart.items.length)return <section className="grid min-h-[60vh] place-items-center px-4 text-center"><div><ShoppingBag className="mx-auto size-10 text-muted-foreground"/><h1 className="mt-4 text-3xl">Your cart is empty</h1><p className="mt-2 text-muted-foreground">Add dishes before checking out.</p><Button asChild className="mt-6"><Link to="/menu">Browse menu</Link></Button></div></section>;
  return <section className="mx-auto max-w-7xl px-4 py-12 lg:px-8"><h1 className="text-4xl md:text-5xl">Checkout</h1><form onSubmit={submit} className="mt-10 grid gap-10 lg:grid-cols-[1fr_380px]"><div className="space-y-9"><fieldset><legend className="text-2xl font-display">Order type</legend><RadioGroup value={orderType} onValueChange={value=>setOrderType(value as "delivery"|"pickup")} className="mt-4 grid grid-cols-2 gap-3"><Label className="flex items-center gap-3 rounded-md border p-4"><RadioGroupItem value="delivery"/>Delivery</Label><Label className="flex items-center gap-3 rounded-md border p-4"><RadioGroupItem value="pickup"/>Pickup</Label></RadioGroup></fieldset><fieldset><legend className="text-2xl font-display">Your details</legend><div className="mt-4 grid gap-5 sm:grid-cols-2"><Field label="Name" name="name" required/><Field label="Phone" name="phone" type="tel" required/><Field label="Email" name="email" type="email"/><Field label="Area" name="area" required={orderType==="delivery"}/>{orderType==="delivery"&&<><div className="sm:col-span-2"><Field label="Delivery address" name="address" required/></div><Field label="Landmark" name="landmark"/></>}</div></fieldset><fieldset><legend className="text-2xl font-display">Payment</legend><RadioGroup value={payment} onValueChange={value=>setPayment(value as "cash"|"bank_transfer")} className="mt-4 gap-3">{PAYMENT_METHODS.filter(method=>method.enabled).map(method=><Label key={method.value} className="flex items-center gap-3 rounded-md border p-4"><RadioGroupItem value={method.value}/>{method.label}</Label>)}</RadioGroup></fieldset><div><Label htmlFor="notes">Order notes</Label><Textarea id="notes" name="notes" className="mt-2 min-h-24"/></div></div><aside className="h-fit rounded-lg border bg-card p-6 shadow-card lg:sticky lg:top-24"><h2 className="text-2xl">Order summary</h2><div className="mt-5 divide-y">{cart.items.map(item=><div key={item.key} className="flex justify-between gap-4 py-3 text-sm"><span>{item.quantity} × {item.name}</span><span>{formatPrice(item.price===null?null:(item.price+item.options.reduce((sum,option)=>sum+option.extra_price,0))*item.quantity)}</span></div>)}</div><div className="mt-4 space-y-2 border-t pt-4 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{formatPrice(cart.subtotal)}</span></div><div className="flex justify-between"><span>Delivery</span><span>{formatPrice(fee)}</span></div><div className="flex justify-between pt-2 text-lg font-bold"><span>Total</span><span>{formatPrice(cart.subtotal+fee)}</span></div></div><div className="mt-5"><Label htmlFor="coupon">Coupon code</Label><Input id="coupon" name="coupon" className="mt-2"/></div>{error&&<p role="alert" className="mt-4 text-sm text-destructive">{error}</p>}<Button type="submit" size="lg" className="mt-5 w-full" disabled={busy}>{busy&&<LoaderCircle className="animate-spin"/>}{busy?"Placing order…":"Place order"}</Button></aside></form></section>;
}

function Field({label,name,type="text",required=false}:{label:string;name:string;type?:string;required?:boolean}){return <div><Label htmlFor={name}>{label}{required?" *":""}</Label><Input id={name} name={name} type={type} required={required} className="mt-2 h-11"/></div>}