import { useSuspenseQuery } from "@tanstack/react-query";
import { createFileRoute } from "@tanstack/react-router";
import { Mail, MapPin, Phone } from "lucide-react";
import { PageHeading } from "@/components/page-heading";
import { Button } from "@/components/ui/button";
import { siteQueryOptions } from "@/lib/site-query";
import { SITE, telHref, whatsappHref } from "@/lib/site";

export const Route = createFileRoute("/contact")({ loader: ({ context }) => context.queryClient.ensureQueryData(siteQueryOptions()), head: () => ({ meta: [{ title: "Contact — Mumtaz Foods" }, { name: "description", content: "Call or visit Mumtaz Foods in Westridge, Rawalpindi." }, { property: "og:title", content: "Contact Mumtaz Foods" }, { property: "og:description", content: "Contact details and directions for Mumtaz Foods." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ContactPage });
function ContactPage(){const {data}=useSuspenseQuery(siteQueryOptions());const settings=data.settings;const whatsapp=whatsappHref(settings?.whatsapp);return <><PageHeading eyebrow="Contact" title="Get in touch"><p>Call us or visit our Westridge location.</p></PageHeading><section className="mx-auto grid max-w-5xl gap-6 px-4 py-14 md:grid-cols-3 lg:px-8"><a href={telHref(settings?.phone)} className="surface-panel p-6"><Phone className="size-6 text-primary"/><h2 className="mt-4 text-xl">Phone</h2><p className="mt-2 text-sm text-muted-foreground">{settings?.phone??SITE.phone}</p></a><a href={settings?.maps_url??SITE.mapsUrl} target="_blank" rel="noreferrer" className="surface-panel p-6"><MapPin className="size-6 text-primary"/><h2 className="mt-4 text-xl">Address</h2><p className="mt-2 text-sm text-muted-foreground">{settings?.address??SITE.address}</p></a>{settings?.email?<a href={`mailto:${settings.email}`} className="surface-panel p-6"><Mail className="size-6 text-primary"/><h2 className="mt-4 text-xl">Email</h2><p className="mt-2 break-all text-sm text-muted-foreground">{settings.email}</p></a>:<div className="surface-panel p-6"><Mail className="size-6 text-primary"/><h2 className="mt-4 text-xl">Orders</h2><Button asChild className="mt-4">{whatsapp?<a href={whatsapp} target="_blank" rel="noreferrer">WhatsApp</a>:<a href={telHref(settings?.phone)}>Call to order</a>}</Button></div>}</section></>}