import { useSuspenseQuery } from "@tanstack/react-query";
import { createFileRoute } from "@tanstack/react-router";
import { Clock3, MapPin, Phone } from "lucide-react";
import { PageHeading } from "@/components/page-heading";
import { Button } from "@/components/ui/button";
import { siteQueryOptions } from "@/lib/site-query";
import { DAY_NAMES, formatTime, SITE, telHref } from "@/lib/site";

export const Route = createFileRoute("/locations")({ loader: ({ context }) => context.queryClient.ensureQueryData(siteQueryOptions()), head: () => ({ meta: [{ title: "Location & Hours — Mumtaz Foods" }, { name: "description", content: "Find Mumtaz Foods in Westridge, Rawalpindi and view current opening hours." }, { property: "og:title", content: "Visit Mumtaz Foods" }, { property: "og:description", content: "Address, directions and opening hours for Mumtaz Foods." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: LocationsPage });
function LocationsPage(){const {data}=useSuspenseQuery(siteQueryOptions());const settings=data.settings;return <><PageHeading eyebrow="Visit us" title="Location & opening hours"/><section className="mx-auto grid max-w-7xl gap-12 px-4 py-14 md:grid-cols-2 lg:px-8"><div><MapPin className="size-7 text-primary"/><h2 className="mt-4 text-3xl">Westridge, Rawalpindi</h2><p className="mt-4 max-w-lg leading-7 text-muted-foreground">{settings?.address ?? SITE.address}</p><div className="mt-7 flex flex-wrap gap-3"><Button asChild><a href={settings?.maps_url ?? SITE.mapsUrl} target="_blank" rel="noreferrer"><MapPin/>Directions</a></Button><Button asChild variant="outline"><a href={telHref(settings?.phone)}><Phone/>Call</a></Button></div></div><div><div className="mb-5 flex items-center gap-3"><Clock3 className="size-7 text-primary"/><h2 className="text-3xl">Opening hours</h2></div><div className="divide-y border-y">{DAY_NAMES.map((day,index)=>{const hours=data.hours.find(item=>item.day_of_week===index);return <div key={day} className="flex justify-between gap-4 py-3 text-sm"><span className="font-semibold">{day}</span><span className="text-muted-foreground">{!hours||hours.is_closed?"Closed":`${formatTime(hours.opens_at)} – ${formatTime(hours.closes_at)}`}</span></div>})}</div></div></section></>}