import { useSuspenseQuery } from "@tanstack/react-query";
import { createFileRoute } from "@tanstack/react-router";
import { Search } from "lucide-react";
import { useMemo, useState } from "react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { ProductCard } from "@/components/product-card";
import { PageHeading } from "@/components/page-heading";
import { siteQueryOptions } from "@/lib/site-query";
export const Route = createFileRoute("/menu")({ loader: ({ context }) => context.queryClient.ensureQueryData(siteQueryOptions()), head: () => ({ meta: [{ title: "Menu — Mumtaz Foods" },{name:"description",content:"Browse the Mumtaz Foods menu for Pakistani food in Rawalpindi."},{property:"og:title",content:"Menu — Mumtaz Foods"},{property:"og:description",content:"Browse the Mumtaz Foods menu and place an order."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}] }), component: MenuPage });
function MenuPage(){ const {data}=useSuspenseQuery(siteQueryOptions()); const [category,setCategory]=useState("all"); const [search,setSearch]=useState(""); const products=useMemo(()=>data.products.filter(p=>p.is_available&&(category==="all"||p.category_id===category)&&(`${p.name} ${p.description??""} ${p.keywords??""}`).toLowerCase().includes(search.toLowerCase())),[data.products,category,search]); return <><PageHeading eyebrow="Order online" title="Our menu"><p>Browse by category, search for a dish, and add your choices to your order.</p></PageHeading><section className="mx-auto max-w-7xl px-4 py-10 lg:px-8"><div className="relative max-w-xl"><Search className="absolute left-3 top-3 size-5 text-muted-foreground"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search dishes" className="h-11 pl-10" aria-label="Search menu"/></div><div className="mt-6 flex gap-2 overflow-x-auto pb-2"><Button onClick={()=>setCategory("all")} variant={category==="all"?"default":"outline"} className="shrink-0 rounded-full">All</Button>{data.categories.map(c=><Button key={c.id} onClick={()=>setCategory(c.id)} variant={category===c.id?"default":"outline"} className="shrink-0 rounded-full">{c.name}</Button>)}</div>{products.length?<div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{products.map(p=><ProductCard key={p.id} product={p}/>)}</div>:<div className="grid min-h-72 place-items-center text-center"><div><Search className="mx-auto mb-3 size-9 text-muted-foreground"/><h2 className="text-2xl">No dishes found</h2><p className="mt-2 text-muted-foreground">Try another search.</p></div></div>}</section></> }
